base_lr: 0.1
batch_size: 80
config: ./config/nturgbd-cross-view/train_joint.yaml
device:
- 0
- 1
- 2
- 3
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.agcn3.Model2
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 60
  num_person: 2
  num_point: 25
model_saved_name: ./runs/ntu_cv_agcn_joint_Srch_CTN
nesterov: true
num_epoch: 70
num_worker: 32
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: train
print_log: true
save_interval: 2
save_score: false
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 30
- 45
- 60
test_batch_size: 40
test_feeder_args:
  data_path: ./data/ntu/xview/val_data_joint.npy
  label_path: ./data/ntu/xview/val_label.pkl
train_feeder_args:
  data_path: ./data/ntu/xview/train_data_joint.npy
  debug: false
  label_path: ./data/ntu/xview/train_label.pkl
  normalization: false
  random_choose: true
  random_move: false
  random_shift: false
  window_size: 270
warm_up_epoch: 0
weight_decay: 0.0006
weights: ''
work_dir: ./work_dir/ntu/xview/agcn_joint_Srch_CTN
